Cidetsi\DepartamentosBundle\Entity\Departamento:
    type: entity
    table: departamento
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
            nullable: false
        abbreviation:
            type: string
            length: 64
            unique: true
            nullable: false
        facultad:
            type: string
            length: 128
            nullable: false
        status:
            type: string
            columnDefinition: ENUM('enabled', 'disabled')
            nullable: false
            options:
                default: 'enabled'
    indexes:
        name_index:
            columns: [ name ]
    uniqueConstraints:
        abbreviation:
            columns: [ abbreviation ]
    oneToMany:
        carreras:
            targetEntity: Carrera
            mappedBy: departamento
            cascade: ["remove"]
    lifecycleCallbacks: {}
