pdf_test:
    pattern: /test.pdf
    defaults: { _controller: CidetsiPdfReportsBundle:Test:test }

pdf_materias:
    pattern: /{id}/lista-materias.pdf
    defaults: { _controller: CidetsiPdfReportsBundle:Materias:list }

pdf_seguimiento:
    pattern: /seguimiento.pdf
    defaults: { _controller: CidetsiPdfReportsBundle:Default:seguimiento }

pdf_nombramiento:
    pattern: /nombramiento.pdf
    defaults: { _controller: CidetsiPdfReportsBundle:Default:nombramiento }
