Cidetsi\DepartamentoBundle\Entity\Carrera:
    type: entity
    table: carrera
    indexes:
        name_index:
            columns: [ name ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
        abbreviation:
            type: string
            length: 64
    manyToOne:
        departamento:
            targetEntity: Departamento
            inversedBy: carreras
            joinColumn:
                name: departamento
                referencedColumnName: id
    lifecycleCallbacks: {}
#    repositoryClass: Cidetsi\BaseBundle\Entity\CarreraRepository
