Cidetsi\DepartamentoBundle\Entity\PlanEstudio:
    type: entity
    table: plan_estudio
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
            nullable: false
        code:
            type: string
            length: 16
            unique: true
            nullable: false
        status:
            type: string
            columnDefinition: ENUM('enabled', 'disabled')
            nullable: false
            options:
                default: 'enabled'
    indexes:
        name_index:
            columns: [ name ]
    uniqueConstraints:
        code:
            columns: [ code ]
    manyToOne:
        carrera:
            targetEntity: Carrera
            inversedBy: planes
            joinColumn:
                name: carrera
                referencedColumnName: id
    lifecycleCallbacks: {}
#
#    manyToMany:
#        materias:
#            targetEntity: Materia
#            joinTable:
#                name: plan_materia
#                joinColumns:
#                    plan:
#                      referencedColumnName: id
#                inverseJoinColumns:
#                    materia:
#                      referencedColumnName: id
