carrera:
    pattern:  /
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:index" }

carrera_create_get:
    pattern:  /agregar
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:createGet" }
    requirements: { _method: get }

carrera_create_post:
    pattern:  /agregar
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:createPost" }
    requirements: { _method: post }

carrera_read:
    pattern:  /{id}/ver
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:read" }

carrera_update_get:
    pattern:  /{id}/editar
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:editGet" }
    requirements: { _method: get }

carrera_update_post:
    pattern:  /{id}/editar
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:editPost" }
    requirements: { _method: post|put }

carrera_delete_get:
    pattern:  /{id}/eliminar
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:deleteGet" }
    requirements: { _method: get }

carrera_delete_post:
    pattern:  /{id}/eliminar
    defaults: { _controller: "CidetsiDepartamentoBundle:Carrera:deletePost" }
    requirements: { _method: post|delete }
