departamento:
    pattern:  /
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:index" }

departamento_create_get:
    pattern:  /agregar
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:createGet" }
    requirements: { _method: get }

departamento_create_post:
    pattern:  /agregar
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:createPost" }
    requirements: { _method: post }

departamento_read:
    pattern:  /{id}
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:read" }

departamento_update_get:
    pattern:  /{id}/editar
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:updateGet" }
    requirements: { _method: get }

departamento_update_post:
    pattern:  /{id}/editar
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:updatePost" }
    requirements: { _method: post|put }

departamento_delete_get:
    pattern:  /{id}/eliminar
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:deleteGet" }
    requirements: { _method: get }

departamento_delete_post:
    pattern:  /{id}/eliminar
    defaults: { _controller: "CidetsiDepartamentoBundle:Departamento:deletePost" }
    requirements: { _method: post|delete }
