Cidetsi\DepartamentoBundle\Entity\Materia:
    type: entity
    table: materia
    indexes:
        name_index:
            columns: [ name ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 128
        code:
            type: string
            length: 16
            unique: true
        type:
            type: string
            columnDefinition: ENUM('curricular', 'no curricular')
        level:
            type: string
            length: 1
    uniqueConstraints:
        code:
            columns: [ code ]
    manyToMany:
        prerequisitos:
            targetEntity: Materia
            joinTable:
                name: prerequisito
                joinColumns:
                    materia:
                      referencedColumnName: id
                inverseJoinColumns:
                    prerequisito:
                      referencedColumnName: id
#    lifecycleCallbacks: {}
#    repositoryClass: Cidetsi\BaseBundle\Entity\CarreraRepository
