Cidetsi\DepartamentosBundle\Entity\Departamento:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 8
                max: 128
            - Regex:
                pattern: "/^[A-Za-z áéíñóúüÁÉÍÑÓÚÜ-]*$/"
                message: The value must be contain only letters and whitespaces
        abbreviation:
            - NotBlank: ~
            - Length:
                min: 3
                max: 32
            - Regex:
                pattern: "/^[A-Za-záéíñóúüÁÉÍÑÓÚÜ-]*$/"
                message: The value must be contain only letters
        facultad:
            - NotBlank: ~
            - Length:
                min: 4
                max: 64
            - Regex:
                pattern: "/^[A-Za-z áéíñóúüÁÉÍÑÓÚÜ-]*$/"
                message: The value must be contain only letters and whitespaces
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, abbreviation]

Cidetsi\DepartamentosBundle\Entity\Carrera:
    properties:
        name:
            - NotBlank: ~
            - Length: { min: 8, max: 128 }
        abbreviation:
            - NotBlank: ~
            - Length: { min: 3, max: 32 }
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]

Cidetsi\DepartamentosBundle\Entity\PlanEstudio:
    properties:
        name:
            - NotBlank: ~
            - Length: { min: 8, max: 128 }
        code:
            - NotBlank: ~
            - Length: { min: 4, max: 16 }
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, code]
